### ISSUE TITLE
plugin dont load (sponge vanilla)

### ISSUE THREAD

**Issue by seema84** [trentech/ChatManager#1]
[Sponge]: Failed to load plugin: com.gmail.trentech.ChatManager.ChatManager (from mods\ChatMa
nager.jar)
java.lang.NoClassDefFoundError: org/spongepowered/api/util/command/CommandCallable
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_66]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_66]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugins(VanillaPluginManager.java:103) [VanillaPluginManager.class:1.8-2.1-DEV-90]
        at org.spongepowered.server.plugin.VanillaPluginManager.loadPlugins(VanillaPluginManager.java:94) [VanillaPluginManager.class:1.8-2.1-DEV-90]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:110) [SpongeVanilla.class:1.8-2.1-DEV-90]
        at net.minecraft.server.dedicated.DedicatedServer.onServerLoad(SourceFile:53) [po.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:97) [po.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:417) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.util.command.CommandCallable
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
        ... 9 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
        ... 9 more

**Comment by trentech** [comment]
This plugin hasn't been updated for the latest Sponge changes yet

**Comment by trentech** [comment]
Update pushed, fixes issue

**Comment by seema84** [comment]
ok thanks
